packageExtensions:
  '@cypress/code-coverage@*':
    peerDependencies:
      '@babel/core': '^7.0.1'
      '@babel/preset-env': '^7.0.0'
      babel-loader: '^8.0.2'
      webpack: '^4 || ^5'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
