name: eslint-config-react-typescript

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable

  eslint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn eslint-config-react-typescript:eslint

  npm:
    if: ${{ github.event_name == 'push' }}
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Publish
        working-directory: packages/eslint-config-react-typescript
        run: >
          yarn config set npmAuthToken $NPM_AUTH_TOKEN;
          yarn npm publish --tolerate-republish;
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/eslint-config-react-typescript.yml'
      - 'packages/eslint-config-react-typescript/**/*'
  push:
    branches: [main]
    paths:
      - '.github/workflows/eslint-config-react-typescript.yml'
      - 'packages/eslint-config-react-typescript/**/*'
