name: Test pull request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install --immutable

  # jest:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         cache: yarn
  #         check-latest: true
  #         node-version: 'lts/*'
  #     - name: Install dependencies
  #       run: yarn install --immutable
  #     - name: Unit test
  #       run: yarn test:jest
  #     - name: Upload coverage
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: test--jest-coverage
  #         path: packages/test/jest/coverage

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-pull-request.yml'
      - 'packages/test/**/*'
